### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by QuLogic** [SciTools/iris#1658]
Most of the simple compatibility stuff is finished (i.e., #1657, etc.). So the question is how to do stuff that is incompatible between 2 and 3?
 * [six](https://pythonhosted.org/six/)
 * [future](http://python-future.org/)

There are a boatload of `iter*` calls, either due to performance or just plain copy & paste. In that regard, it would be much nicer to just use Python 3 syntax via `future`. Any thoughts on the two?

Remaining items:
 * [x] #1701 - Python 3 installable
 * [x] #1702 - File I/O in contexts
 * [x] #1709 - Portable comparisons
 * [x] #1770 - Handle changes to builtins
 * [x] #1771 - Handle changes to exceptions and warnings
 * [x] #1773 - Handle binary I/O consistently
 * [x] #1772 - Add hashes to some types where necessary
 * [x] #1777 - Fix some methods due to inheritance changes
 * [x] #1778 - Ensure tests work on sorted data
 * [x] #1774 - Fix some GRIB issues
 * [x] #1782 - [Fix Unicode handling](https://github.com/QuLogic/iris/tree/py3k-unicode)
 * [x] #1781 - Fix some new stuff in PP loader
 * [x] #1787 - Python 3 compatibility for C extension
 * [x] #1842 - [Final tweaks and Travis enablement](https://github.com/QuLogic/iris/tree/py3k)

**Comment by QuLogic** [comment]
Ping?

**Comment by rhattersley** [comment]
We've used `six` in Cartopy, so sticking with that would avoid the need for yet another dependency.

**Comment by QuLogic** [comment]
Ah, it seems it's a good thing I started trying to do it that way already, then.

**Comment by QuLogic** [comment]
Currently reaching about 90% test passes now, but most of the failures are now due to Grib's issues, or with something I don't yet understand.

**Comment by pelson** [comment]
> Currently reaching about 90% test passes now, but most of the failures are now due to Grib's issues, or with something I don't yet understand.

It isn't unreasonable to state that GRIB is not supported on Python3. We do precisely that for Windows. GRIB is an optional dependency for Iris after all.

**Comment by ajdawson** [comment]
>It isn't unreasonable to state that GRIB is not supported on Python3. We do precisely that for Windows. GRIB is an optional dependency for Iris after all.

Agreed, with the following caveat: When we announce Python 3 support we must make sure to declare very openly which components are not supported.

**Comment by QuLogic** [comment]
Hrm, you're right that's how it's documented, but the tests seem to disagree.

**Comment by QuLogic** [comment]
What is the encoding for the text fields in the NAME, NIMROD formats?

**Comment by QuLogic** [comment]
```
----------------------------------------------------------------------
Ran 3432 tests in 86.103s

FAILED (SKIP=16, errors=4, failures=6)
```

99% there...

**Comment by rhattersley** [comment]
> 99% there...

:clap: Impressive. :smile:

**Comment by QuLogic** [comment]
I've got about [8 branches](https://github.com/QuLogic/iris/branches/yours) split out into common changes and ready to make PRs. But I'm not sure how co-dependent they are, so I'm not going to open any PRs until the other 4 are merged.

**Comment by rhattersley** [comment]
If there are still multiple steps to achieve this then perhaps a checklist in the description, or split it out into multiple issues.

**Comment by rhattersley** [comment]
Thanks for adding the checklist @QuLogic :smile:

**Comment by QuLogic** [comment]
Hmm, looks like there are no [3.3 dependencies](https://travis-ci.org/QuLogic/iris/jobs/78526555) in conda. And a few missing things [in 3.4, too](https://travis-ci.org/QuLogic/iris/jobs/78526559).

**Comment by pelson** [comment]
> And a few missing things in 3.4, too.

https://github.com/SciTools/conda-recipes-scitools/blob/master/pyugrid/meta.yaml#L14

> Hmm, looks like there are no 3.3 dependencies in conda.

I decided to keep the matrix small. It is easy enough to fix, but has the cost of an extra load of built distributions. Given we want to keep the channel as small as possible, do you feel that py33 is critical @QuLogic?

**Comment by QuLogic** [comment]
Well, that's up to you. Cartopy, biggus, etc. are tested on 3.3.

**Comment by QuLogic** [comment]
It turned out to be pretty easy to split apart the smaller branches, so there are 5 new PRs to review.

**Comment by QuLogic** [comment]
The [first build](https://travis-ci.org/QuLogic/iris/builds/81096818) to pass on Travis without trouble is finally up (except 3.3 has no conda deps.)

**Comment by pelson** [comment]
> The first build to pass on Travis without trouble is finally up (except 3.3 has no conda deps.)

Is there a good reason to support py33 (other than the fact that we *can*)? Otherwise, I'm inclined to keep our lives as simple as possible and state py27 / py34 / (py35) support only.

**Comment by QuLogic** [comment]
It used to be the latest supported on RHEL, but now software collections has a 3.4 backport, so perhaps it is not so necessary.

**Comment by pp-mo** [comment]
As @pelson already suggested, we probably only need support Python 2.7 and 3.4 : [comment](https://github.com/SciTools/iris/issues/1658#issuecomment-141640007)
Against 3.3 : few people would specifically need it
Against 3.5 : available conda builds are too restrictive, especially regarding our current need for matplotlib=1.3.1.  It will make much more sense to progress this when we have fixed our testing dependency on an older matplotlib version (or at least updated it),  but that has to be future work, not a pre-requisite for 1.9.

So **just 2.7 + 3.4**  sounds like a a nice simple goal
(= stated support; tests work; testing in Travis)

**@QuLogic @pelson @rhattersley are we all agreed that will be good enough ?**

**Comment by QuLogic** [comment]
Sounds good to me. I think most of the hard work for updating matplotlib has to do with cartopy, but that's already in progress.

**Comment by rhattersley** [comment]
I'd be very happy with 2.7 + 3.4. :+1:

**Comment by rhattersley** [comment]
So... this is done?!? :grin:

**Comment by pp-mo** [comment]
> So... this is done?!? :grin:

I believe it is : everything here has now been included somewhere else.
Agreed @QuLogic ?

**Comment by QuLogic** [comment]
Pretty much; I was holding off unless any last minute issues came up.

**Comment by pelson** [comment]
:tada: :tada: - woohoo! Welcome to the 21st century :stuck_out_tongue_winking_eye: ! :+1:

**Comment by rhattersley** [comment]
> Pretty much; I was holding off unless any last minute issues came up.

Superb! Well done everyone... and especially @QuLogic! :clap: 

I'd _love_ to close this PR now, but I'd rather @QuLogic did it. (If anything else comes up I think we should just raise a specific issue.)

**Comment by QuLogic** [comment]
:birthday: :tada:

**Comment by rhattersley** [comment]
:metal:

**Comment by ocefpaf** [comment]
Thanks all! And special thanks to Elliott!

I am looking forward for the next release!

Iris was the last major dependency I needed to move to py3.
