### ISSUE TITLE
Replace iris.units with cf_units

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#1822]
Given  [cf_units](https://github.com/SciTools/cf_units) at v0.1.1, and our own #1820, it should very soon be possible to deprecate iris.unit, and completely replace internal usage with cf_units.
**So let's do that for iris v1.9**

(cf: [@dkillick comment](https://github.com/SciTools/iris/pull/1820#issuecomment-152465694), [@dkillick moderated statement](https://github.com/SciTools/iris/pull/1820#issuecomment-152469215))
@pelson says this has since been discussed + basically agreed.

Necessary :
 * [x] complete [cf_units#36 tidyup](https://github.com/SciTools/cf_units/pull/36)
 * [x] fix #1820 replace iris.unit], and restore ```iris.unit```
   * (it currently completely *removes* it = good for proof-of-principle, but not for release) .
 * [x] #1821 deprecate iris.unit (issue warning on import)

**Comment by pp-mo** [comment]
Unfortunately we are still not quite done...
 * there is no whatsnew entry
 * there is no addition to the required dependencies documentation in INSTALL

**Comment by QuLogic** [comment]
Also related, because of the import for pyke rule compilation stuff, this change means that `cf_units` is required at _install_ time, not just runtime, which maybe should be noted in `setup.py`.

**Comment by pp-mo** [comment]
> @QuLogic the import for pyke rule compilation stuff ... required at install time
I think in fact that is *not* strictly necessary :  You don't have to run "python setup.py pyke_rules" during installation.  If not, it simply builds them at the first usage -- except, I think we have a test that imports the built rules module directly and fails if it is not there.

**Comment by pp-mo** [comment]
> @QuLogic It does get called if you run pip install ..

I guess so.

But I don't see how this makes much difference, as our installer documentation doesn't make any distinction between runtime and install-time dependencies.
 \- or am I missing something here ??

**Comment by pp-mo** [comment]
>  cf_units is required at install time
> It does get called if you run pip install ..

On looking into this, it is listed as a full (non-optional) dependency (well, it is now.. #1863).
The INSTALL section "Installing from source"  already suggests you will need all the full dependencies ***before*** install.
So I think that just covers it, no more required.

**Comment by pp-mo** [comment]
All sorted, under #1863
