### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by pelson** [SciTools/iris#3038]
Planning to release a v2.1.0 over the next week or so (target 6th June 2018).

Reminders for me:

 - [x] Open a v2.1.1 milestone
 - [x] Ensure the version switcher code is in-place in the iris docs (@pelson re https://github.com/SciTools/scitools.org.uk/pull/191)
 - [x] Update the what's new
    - [x] Ensure the docs/iris/src/_templates/index.html link to the what's new is updated
    - [x] Write a what's new for #2943.
    - [x] Write a what's new for #3010.
    - [x] Double check that the what's new is representative of all PRs that actually got merged.
 - [x] Ensure the URL of the image in the README is updated as per https://github.com/SciTools/iris/pull/3040#discussion_r192319809
 - [x] ~Ensure a what's new directory exists for v2.2 (and think about whether this process continues to make sense)~ (note: this doesn't make sense, as you have to have a file in order to add the directory, and there isn't any what's new yet. Personally, I see the what's new stuff flawed. I'll address this over the next few weeks, but not for v2.1)
 - [x] Update the version strings #3051 (also see https://github.com/SciTools/iris/issues/3038#issuecomment-395474464)
 - [x] Update the cf-standard names
 - [x] Merge any existing release branches (and close some off)
 - [x] Push docs to scitools.org.uk
 - [x] Push sdist to pypi
 - [x] Update conda-forge
 - [x] Announce on mailing-list
 - [x] Write this down in a release checklist
 - [x] Close the v2.1.0 milestone

**Comment by pelson** [comment]
#3045 Fixes the version switcher and updating the README image URL.

**Comment by pelson** [comment]
#3044 implements the what's new.

**Comment by pelson** [comment]
#3046 updates the cf-standard-names

**Comment by pelson** [comment]
#3047 closes the existing release branches

**Comment by pelson** [comment]
#3050 adds the what's new for #3010, and improves branding/strap-line for Iris

**Comment by pelson** [comment]
Handing over some of this to @dkillick.

**Comment by pelson** [comment]
Pushed version bumps for:

``v2.1.1dev0``: d888eb6b
``v2.2.0dev0``: 51e0d158

**Comment by pelson** [comment]
Docs PRs: https://github.com/SciTools/scitools.org.uk/pull/204 and https://github.com/SciTools/scitools.org.uk/pull/201

**Comment by pelson** [comment]
I've just written down a high-level overview of the release checklist in https://github.com/SciTools/iris/wiki/Release-checklist-guidance. I hope this is useful and not too much detail. I've xrefd this issue so that people can see an example of it used in practice. cc @SciTools/iris-devs

**Comment by kaedonkers** [comment]
@pelson Can I suggest an addition to the release checklist:
- [ ] Announce on Twitter

![Met Office Science](https://twitter.com/MetOffice_Sci/status/1006539998861119489) tweeted about the release of Iris 2.1 on our behalf and have encouraged us to do so again with each release. This seems like the most sensible place to make sure we remember to do that.

**Comment by rcomer** [comment]
Looks like Iris 2.1.0 has not yet been announced on the users' google group...

**Comment by pelson** [comment]
> Looks like Iris 2.1.0 has not yet been announced on the users' google group...

Good point. This is my fault for not specifying the "user's mailing list", @dkillick announced it on the dev mailing list... I've just posted something on the users list now.

@kaedonkers -  I'm reluctant to make it one of the checklist items, but definitely support improved PR around releases where appropriate.
