### ISSUE TITLE
Release v2.2.0

### ISSUE THREAD

**Issue by dkillick** [SciTools/iris#3193]
We're planning to get Iris v2.2.0 released by the end of this week. For specifics of what's included in this release, see the [associated milestone](https://github.com/SciTools/iris/milestone/38). Note that most of the work is already done, so the milestone is nearly empty (hurrah!).

Still to do...

- [x] public contiguity checking PR (#3144)
- [x] whatsnew (#3192)
- [x] Update the cf-standard names (@pp-mo & @kaedonkers – #3199)
- [x] Merge any existing release branches (and close some off) (@corinnebosley – #3197)
- [x] Update the version strings (@dkillick – #3198)
- [x] Make the tag
- [x] Update the version string again (to `2.3.0dev0`) (@corinnebosley – #3200)
- [x] Push docs to scitools.org.uk (@corinnebosley - https://github.com/SciTools/scitools.org.uk/pull/213)
- [x] Push sdist to pypi
- [x] Update conda-forge (@corinnebosley - https://github.com/conda-forge/iris-feedstock/pull/41)
- [x] Announce on mailing-list
- [x] Close the v2.2.0 milestone 

cc @SciTools/iris-devs

**Comment by dkillick** [comment]
Done! 🎉

**Comment by pp-mo** [comment]
Yee-hah ! :cowboy_hat_face:
