### ISSUE TITLE
[PI] Quality Flag Handling

### ISSUE THREAD

**Issue by abooton** [SciTools/iris#3358]
Provision of support for "Quality Flags"
---
**Required work**
The relevant PRs to implement support for quality flags are below:

- [x] Include support for standard_name modifiers #3393
- [x] Decide on how to handle units and standard name modifiers #3408
- [x] Include support for Ancillary Variables #3422
- [x] Included loading/saving of Ancillary Variables (outstanding issue #3473)
- [x] Support for status flags (outstanding issue #3474)

---
**Description:**

Quality flags can be encoded in CF compliant data by using the "ancillary variable" and with "flag" values.    This convention allows for a more explicit descriptions of the "quality flags" that one would like to associate with the data.  (See snipped below for example)

According to the CF conventions:  http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#ancillary-data

However, at present, there are a couple of small issues when creating a "flag" auxiliary coordinate, as the current implementation does allow the issues below to be correctly handled:
1) The status_flag standard name should be recognised as so if the cube name is also a standard_name.  (At present it come in as a long name.) See Appendix C, Standard Name Modifiers.
2) The ancillary_variable should be a local attribute, as it is directly associated the specific data. (i.e. like a latitude coord would be local to the data).
3) status_flags should not have units (they are described instead).  See Appendix C, Standard Name Modifiers.

""
![image](https://user-images.githubusercontent.com/19527482/61215240-2ab83800-a702-11e9-93c8-b6500c39479c.png)

The following code was used to generate the flag coordinate, the meta data for which is shown above:

![image](https://user-images.githubusercontent.com/19527482/61217403-876a2180-a707-11e9-9751-91c134516b7c.png)

**Comment by lbdreyer** [comment]
Delaying this til the next Iris release (Iris 3).

Unfortunately we have run out of time to properly implement this (in the way we want to which would include an improvement to how Cube dimensional metadata is handled), so this will instead be included in the Iris 3 release. Hopefully that shouldn't be an issue as Iris 3 is only a month away!

**Comment by lbdreyer** [comment]
The relevant PRs to implement support for quality flags are below:

* Include support for standard_name modifiers #3393 
* Decide on how to handle units and standard name modifiers #3408
* Include support for Ancillary Variables #3422
* Included loading/saving of Ancillary Variables (outstanding)
* Support for status flags (outstanding)

**Comment by stephenworsley** [comment]
In the following line in the netCDF file:
```
air_temperature:coordinates = "flag forecast_period forecast_reference_time time" ;
```
it seems as though the appearance of `flag` is probably a mistake. The var_name `flag` should only be referenced by `ancillary_variables`. i.e. in the line:
```
air_temperature:ancillary_variables = "flag" ;
```

**Comment by stephenworsley** [comment]
A "what's new" entry has now been added by #3801 (and fixed by #3816). This closes the issue.
