### ISSUE TITLE
Pull-request checklist needs a revamp

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3453]
Problems spotted :
  1. [ ] "Iris tests may be run with python setup.py test "  -- is this still true, or is there a bette way ?
  1. [ ] "There is a python module for checking pep8 compliance: python-pep8" -- should now be referring to **flake8**
  1. [ ] "the files ./conda-requirements.yml and ./minimal-conda-requirements.yml are used to define the software environments"  -- now uses combined requirements process in iris/requirements
  1. [ ] "test-images-scitools is a github project containing reference plot images" -- has moved
  1. [ ] "see Graphics tests" -- docs-page still incomplete https://scitools.org.uk/iris/docs/latest/developers_guide/tests.html#graphics-tests

**Comment by rcomer** [comment]
I was rummaging in the image tests today (as you do) and noticed there seems to be an option for displaying the figures that you are testing:
https://github.com/SciTools/iris/blob/3b4a00d0736858139c395fac66de349c4f02c95a/lib/iris/tests/__init__.py#L140-L143

This would be useful information to have in the proposed new _How To Run the Tests_ section.

**Comment by tkknight** [comment]
Fixed by #3852 and other earlier PR's.
