### ISSUE TITLE
Strip out Python 2 from Iris src code

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#3457]
Iris 3 will be a Python 3 only release so we need to remove all Python 2 support.

This will include removing all the `six` code and any other remaining Python 2 handling.

Note, we have already dropped testing with Python 2 (see #3446)

Note, this could be split into multiple smaller issues.

---
### Acceptance Criteria:
- [x] Remove all `six` code - @trexfeathers #3497 
- [x] Remove unnecessary `__future__` imports & address `iris.tests.test_coding_standards.TestFutureImports` - @stephenworsley #3505
- [x] Remove unnecessary `super` arguments - @stephenworsley #3506
- [x] Remove/replace all Python2 specific code  @stephenworsley #3507 
- [x] Address all code that deals with Python3 as optionally supported @stephenworsley #3507 
- [x] Remove Python2 class references to `object`, see [here](https://realpython.com/python3-object-oriented-programming/#how-to-define-a-class-in-python) for an example @stephenworsley #3511 
- [ ] Merge feature branch `py2_strip` to `master`
- [ ] Delete feature branch `py2_strip`

**Comment by bjlittle** [comment]
Remove the `iris.tests.test_coding_standards.TestFutureImports` class, see [here](https://github.com/SciTools/iris/blob/master/lib/iris/tests/test_coding_standards.py#L346-L403).

**Comment by bjlittle** [comment]
Also, grep through the code base and inspect hits for:

- `grep -ri "python3"` and `grep -ri "python 3"`
- `grep -ri "python2"` and `grep -ri "python 2"`

**Comment by stephenworsley** [comment]
For Python 3 relevent `__future__` imports, see https://docs.python.org/3/library/__future__.html

**Comment by stephenworsley** [comment]
Since it is conceivable that we might introduce `__future__` imports at a later date, it might be worthwhile skipping this test, removing Python 2/3 specific references, and leaving its skeleton for future reference.

**Comment by trexfeathers** [comment]
An example of some of the 'Python 2 specific code' we might be looking for:
```python
        with self.assertRaisesRegex(TypeError,
                                    # exactly == Py2, positional == Py3
                                    'takes (exactly )?1 (positional )?'
                                    'argument '):
```

**Comment by stephenworsley** [comment]
An idea for how to find python 2/3 specific code would be to search through try/except statements. Having done a little bit of this I found this statement: https://github.com/SciTools/iris/blob/1a882f1bf7f470d6e1a16cb9937da53eb8573dcf/lib/iris/tests/unit/analysis/maths/test_divide.py#L31-L34 which seems to be python 2/3 specific issue relating to a change in behaviour of `operator` but with no other indicators that it relates to python 2/3.
