### ISSUE TITLE
Move grib tests from iris into iris-grib

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/iris#3476]
Currently, there are some tests in iris that test grib handling but would preferably live in iris-grib. For instance #3469 has skipped 3 tests that fail due to needing changes in iris-grib that have not yet been released.
- [x] tests/`__init__.py`: move TestGribMessage class (do this last!) **@lbdreyer** #3672 https://github.com/SciTools/iris-grib/pull/203
- [x] tests/system_test.py  **@pp-mo** #3662
- [x] tests/test_grib_load_translations.py  **@pp-mo** https://github.com/SciTools/iris-grib/pull/191 #3663
- [x] tests/test_grib_save.py **@lbdreyer** https://github.com/SciTools/iris-grib/pull/198 #3669
- [x] tests/test_grib_save_rules.py **@lbdreyer** https://github.com/SciTools/iris-grib/pull/195 #3666
- [x] tests/test_uri_callback.py **@lbdreyer** https://github.com/SciTools/iris-grib/pull/194 #3665
- [x] tests/integration/test_grib2.py **@lbdreyer** https://github.com/SciTools/iris-grib/pull/192 #3664
- [x] tests/integration/test_grib_load.py @pp-mo #3670 https://github.com/SciTools/iris-grib/pull/200
- [x] tests/integration/test_pickle.py **@pp-mo**  #3671 https://github.com/SciTools/iris-grib/pull/201
- [ ] tests/integration/format_interop/: leave for now?

**Comment by lbdreyer** [comment]
Related issues: #2860 #3477 #3375

**Comment by lbdreyer** [comment]
@pp-mo we could use this to track who is working on what

**Comment by pp-mo** [comment]
LINKS + notes (**WIP** editing as I go)

 - tests/`__init__.py`: move [TestGribMessage class](https://github.com/SciTools/iris/blob/836244ea92d4dff32e411be329524234a5f9f6dd/lib/iris/tests/__init__.py#L1124) (do this last!)
  * Iris usage:
    * tests/integration/grib2/test_grib2 : TestPDT11 TestGDT5
    * tests/test_grib_save : TestLoadSave
 - tests/system_test.py [system_test_grib_patch](https://github.com/SciTools/iris/blob/836244ea92d4dff32e411be329524234a5f9f6dd/lib/iris/tests/system_test.py#L79)
  * Don't understand scope of this : where is the magic "patch" this is testing, is it just ancient + obsolete ??
 - [tests/test_grib_load_translations.py](https://github.com/SciTools/iris/blob/836244ea92d4dff32e411be329524234a5f9f6dd/lib/iris/tests/test_grib_load_translations.py)
  * Notes:  OK should port simply.  But is old + grib1-specific I think.  The grib2 functionality in FakeGribMessage is no longer used
 - [tests/test_grib_save.py](https://github.com/SciTools/iris/blob/836244ea92d4dff32e411be329524234a5f9f6dd/lib/iris/tests/test_grib_save.py)
  * Notes:
    * uses "iris.tests.TestGribMessage".
    * TestLoadSave look ok to me
       - some load, some save, possibly better to re-organise ?
    * TestCubeSave
       - some ancient stuff in here
 - [tests/test_grib_save_rules.py](https://github.com/SciTools/iris/blob/836244ea92d4dff32e411be329524234a5f9f6dd/lib/iris/tests/test_grib_save_rules.py)
 - tests/test_uri_callback.py [test_grib_callback](https://github.com/SciTools/iris/blob/836244ea92d4dff32e411be329524234a5f9f6dd/lib/iris/tests/test_uri_callback.py#L18)
 - ~tests/integration/test_grib2.py~ @lbdreyer ...
 - [tests/integration/test_grib_load.py](https://github.com/SciTools/iris/blob/836244ea92d4dff32e411be329524234a5f9f6dd/lib/iris/tests/integration/test_grib_load.py)
 - tests/integration/test_pickle.py [TestGribMessage](https://github.com/SciTools/iris/blob/836244ea92d4dff32e411be329524234a5f9f6dd/lib/iris/tests/integration/test_pickle.py#L44)
 - ~tests/integration/format_interop/:~ **leave for now?**

**Comment by pp-mo** [comment]
All dealt with, delivered in release v0.15.1
