### ISSUE TITLE
[PI] Cube operations support for Ancillary Variables

### ISSUE THREAD

**Issue by pp-mo** [SciTools/iris#3483]
Content update 2019-12-09
The notes below identify various problem areas, which leads to the following division of sub-tickets 
(Todo list) :
  * [x] `Cube.copy` and `Cube.__eq__` : #3546
  * [x] cube indexing = `Cube.__getitem__` : #3548
  * [x] concatenate and merge : #3552
  * [x] cube arithmetic : (cf. #3478)
  * [x] statistics = collapse/aggregated_by/rolling_window : #3549
  * [x] "all other cube operations" : ref #3554 . Includes :
    * 'other' indexing-like cube methods : `Cube.subset` and `Cube.intersection`
    * regrid/interpolate : `Cube.regid`, `Cube.interpolate` and all schemes code
    * `Cube.xml()`

----
**Original summary**

Followon from #3422 

A bunch of cube operations are not respecting Ancillary Variables.
We are deferring these issues from #3422.
See [this comment to \#3422](https://github.com/SciTools/iris/pull/3422#issuecomment-545421796).

In principle, for most of these things the handling should be the same as for AuxCoords and (probably) CellMeasures.  Unfortunately, it seems that there are some nasty outstanding bugs relating to CellMeasures anyway -- e.g. they don't survive cube.copy() !.

At least these operations need fixing :
  * ~cube indexing (`__getitem__`) is discarding AVs, even when they don't map to the indexed dimension~
  * ~cube.copy() is discarding AVs~
    * ~and it is also discarding CellMethods !~
  * ~cube equality (`__eq__`) is ignoring AVs~
    * ~but not AuxCoords.~
    * ~CellMethods I'm not sure ?~
  * **updated 2019-11-22** above core cube ops are now fixed
    * [copy](https://github.com/SciTools/iris/pull/3546) : [indexing](https://github.com/SciTools/iris/pull/3548) : [equality](https://github.com/SciTools/iris/pull/3536)/[equality#2](https://github.com/SciTools/iris/pull/3546)
    * however fixing those probably has knock-ons elsewhere within this list of things to fix ..
  * cube arithmetic is discarding AVs
    * but not AuxCoords.
    * CellMethods I'm not sure ?
    * ( note : probably fixed by fixing 'copy' ? )
  * cube.collapsed() is discarding AVs
    * even when they don't map to collapsed dimensions
    * for AuxCoords it applies the same aggregator as the main data
    * for CellMethods I'm not sure
  * cube.xml ignores AVs
    * also CellMethods ?
    * but not AuxCoords.

There is also a longer list of 'similar' cube operations which should be checked, some of which may be fixed "automatically" by addressing the above ones, and others possibly not :
  * stats : aggregated_by; rolling_window
  * regrid-like : regrid, interpolate, 
  * index-like : extract, subset, intersection, 

Notes:
   1. In all the cases where the result dimensions are different from the input, we need to check for correct handling both when Ancillary Variables ***are*** mapped over the modified/lost dimensions, ***and*** when they are not.
   1. in some cases, the appropriate solution may *not* be the same for all of AuxCoords, CellMeasures and Ancillary Variables.
      * for example, AuxCoords are regridded with the main data : Probably is also appropriate for Ancillary Variables (the nature and meaning of which is not known), but arguably *not* to Cell Measures (where it is).

----

NOTE:
It may well prove appropriate to fix these issues by grouping together AuxCoords, CellMeasures and AncillaryVariables, and handling them all similarly.

**Comment by pp-mo** [comment]
Additionally, other cube-based operations, outside the Cube class, could potentially be affected.
Basically anything that creates an output cube by copying elements from an input, which may now be incomplete, especially regrid-like routines.
Suggested areas :
  `iris.analysis.calculus`
  `iris.analysis.maths`
  `iris.analysis.cartography.project()`
  `iris.analysis.trajectory.interpolate()`

**Comment by pp-mo** [comment]
As also mentioned [here](https://github.com/SciTools/iris/pull/3422#issuecomment-545480015), we also need changes to correctly handle AVs in the concatenate and merge operations.  
That can live here for now, but in future it could be useful to split it out to a separate work ticket.

**Comment by trexfeathers** [comment]
`cube.copy` is being addressed in #3546, here are some notes on the downstream effects:

- `analysis.PercentileAggregator.post_process` ✔
    - used in `collapsed`, which is also being modified to retain AV's in #3549 so these should be released together
    - allows the end result of a percentile aggregation collapse to retain AV's, CM's
    - for this there are no considerations needed about retention/discarding depending on the collapsed dimension
- `analysis.maths._math_op_common` ✔
    - allows AV's and CM's to be retained after performing arithmetic on a cube - the first cube if multiple cubes are involved
    - no foreseen issues
- `analysis.calculus.cube_delta` ✔
    - actually needs this `copy` fix now that `__getitem__` has been fixed in #3548 - these should both be fixed together
    - (otherwise behaviour is different is coord(s) are circular or not)
- `analysis.calculus._curl_subtract` ✔
    - used in the production of curl cubes
    - original dimensions are retained in the output curl cubes, so no unusual consequences expected if the output cubes now include AV's/CM's
- `analysis._regrid.CurvilinearRegridder` ❌
    - see #3554
- `analysis.trajectory.UnstructuredNearestNeigbourRegridder`, also `.__call__` method ❌
    - see #3554
- `analysis._grid_angles.rotate_grid_vectors` ✔
    - original dimensions are retained in the output cubes, so no unusual consequences expected in the output cubes now include AV's/CM's
- `analysis._grid_angles.rotate_winds` ✔
    - see points on `analysis._grid_angles.rotate_grid_vectors`
- `experimental.stratify.relevel` ❌
    - used for interpolation over a dimension denoted with levels
    - see #3554

**Comment by bjlittle** [comment]
@abooton As a minimum contract, cube arithmetic clears:
- cell methods
- cell measure
- ancillary variables
- the phenomenon name
- the `STASH` attribute
For `iris` 3.1 we can extend the cube arithmetic behaviour to maintain cell measures and ancillary variables, but happy that this is out of scope for 3.0

**Comment by bjlittle** [comment]
See issue #4872, which captures follow-on work as a separate task.
