### ISSUE TITLE
[PI] Developer Guide Overhaul

### ISSUE THREAD

**Issue by tkknight** [SciTools/iris#3824]
## 📚 Documentation

The Developer Guide (see sidebar on https://scitools-iris.readthedocs.io/en/latest/) is in need of an overhaul, including:

- General structure of the contents
- New page for detailing how to get started developing
- New page for more info on how to run the tests
- Finalise the graphics tests documentation
- Review and update the git instructions

This is a parent issue that may resolve: 

  1. [x] #2170. Developer guide - image testing
  1. [x] #2331. Complete Graphics Testing Documentation
  1. [x] #3453. Pull-request checklist needs a revamp
  1. [x] #314. Documenting the addition of a gallery entry
  1. [x] #2902. Improve the docs around adding/extending/replacing a graphics test

**Comment by trexfeathers** [comment]
Is it OK to now move this to [3.1](https://github.com/SciTools/iris/projects/26)? Or are the remaining issues fairly trivial to finish?
