### ISSUE TITLE
Iris 3.2.0 Deprecations

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#4394]
## 📰 Custom Issue
We require to consider and include any functional deprecations that we want to include for the forthcoming `iris` 3.2.0 release. 

**Existing Deprecations**
- [x] [iris.util.as_compatible_shape](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/util.html#iris.util.as_compatible_shape). Deprecated in 3.0.0 (#4513)

**Proposed New Deprecations for 3.2**
- [x] [iris.util.approx_equal](https://scitools-iris.readthedocs.io/en/stable/generated/api/iris/util.html#iris.util.approx_equal).
     Proposed by @rcomer, see [comment](https://github.com/SciTools/iris/issues/4394#issuecomment-996780194) below. Agreed
     (#4514)
- [x] [iris.fileformats.abf](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/fileformats/abf.html).
     Proposed by @bjlittle. Agreed (remove - ask community if this is an issue)
     Also see https://github.com/SciTools/iris-abf and https://github.com/SciTools/iris/pull/3657
     (#4515)
- [x] [iris.fileformats.dot](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/fileformats/dot.html).
     Proposed by @bjlittle. Agreed (remove - as above)
     (#4515)
- [x] iris.experimental.raster. 
     Proposed by @bjlittle. Agreed (remove - as above)
     (#4525)
     (#4545)
- [x] `iris.experimental.regrid_conservative` (and optional dependency `esmpy`).
     Proposed by @pp-mo. Agreed (remove - as above) Functionality available/equivalent in `iris-esmf-regrid`.
     (#4551)
- [x] `iris.experimental.regrid`
    Proposed by @pp-mo. Agreed (this will be moved)
     (#4548)

**Investigate**
- [x] @rcomer proposal for `intersection_of_cubes` vs `extract_overlapping`, see [comment](https://github.com/SciTools/iris/issues/4394#issuecomment-1011240999) below.
     (#4541)

**Related**
- See https://github.com/SciTools/iris/issues/3515

**Further**
- We want to review and update the [Deprecation Policy](https://scitools-iris.readthedocs.io/en/latest/developers_guide/contributing_deprecations.html) in our documentation (will also affect our page on [Code Maintenance](https://scitools-iris.readthedocs.io/en/stable/userguide/code_maintenance.html))
- Reference https://numpy.org/neps/nep-0023-backwards-compatibility.html

**Comment by rcomer** [comment]
How about [iris.util.approx_equal](https://scitools-iris.readthedocs.io/en/stable/generated/api/iris/util.html#iris.util.approx_equal)?  It appears to do the same job as [math.isclose](https://docs.python.org/dev/library/math.html#math.isclose).  Also I can't find any tests for it...

**Comment by bjlittle** [comment]
Let's collate here the proposed list of deprecation's that we want to consider/review/action for `iris` 3.2.

This is a WIP...

- [ ] `numpy` legacy array printing. See #3048 and #4486
- [ ] [iris.util.approx_equal](https://scitools-iris.readthedocs.io/en/stable/generated/api/iris/util.html#iris.util.approx_equal). Proposed by @rcomer above
- [ ] [iris.util.as_compatible_shape](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/util.html#iris.util.as_compatible_shape). Deprecated in 3.0.0
- [ ] [iris.fileformats.abf](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/fileformats/abf.html)
- [ ] [iris.fileformats.dot](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/fileformats/dot.html)
- [ ] iris.experimental.raster

**Comment by rcomer** [comment]
I also *think* that [iris.analysis.maths.intersection_of_cubes](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/analysis/maths.html#iris.analysis.maths.intersection_of_cubes) and [CubeList.extract_overlapping](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/cube.html#iris.cube.CubeList.extract_overlapping) do very similar things, though the latter is more flexible and better documented.

**Comment by lbdreyer** [comment]
I'm a little concerned by a couple of the proposed deprecations. In particular: iris.fileformats.abf and iris.experimental.raster. I have helped users that were using each of those bits of functionality. That being said, I don't know if they are still using it! 

> ask community if this is an issue

Did you discuss how best to approach this? Do we want to do this prior to deprecation, or will there be the option to put it back in if we find that removing it causes enough problems

**Comment by wjbenfold** [comment]
> Did you discuss how best to approach this? Do we want to do this prior to deprecation, or will there be the option to put it back in if we find that removing it causes enough problems

We suggested that the deprecation notices for the functionality we're not sure about included prompting the community to let us know if it was a concern to them so that we can remove the deprecation or discuss how to preserve the functionality another way.

**Comment by wjbenfold** [comment]
> I also _think_ that [iris.analysis.maths.intersection_of_cubes](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/analysis/maths.html#iris.analysis.maths.intersection_of_cubes) and [CubeList.extract_overlapping](https://scitools-iris.readthedocs.io/en/latest/generated/api/iris/cube.html#iris.cube.CubeList.extract_overlapping) do very similar things, though the latter is more flexible and better documented.

I agree with this assessment. My only reservation about doing this is that there are probably places where a single line use of `intersection_of_cubes` is replaced by maybe three or four lines using `extract_overlapping` e.g.

```
cube1, cube2 = cube1.intersection_of_cubes(cube2)
```
becomes
```
cubes = CubeList([cube1, cube2])
coords = ["latitude", "longitude"]     #This might be much harder if you're relying on the behaviour of "every coord except the single-valued ones"
intersections = cubes.extract_overlapping(coords)
cube1, cube2 = (intersections[0], intersections[1])
```

For: It's duplicated functionality and we could be making users use the more flexible, better documented, better written one.
Against: It'll take some people a couple of minutes to move their code over from the old to the new and it'll be more lines of code.

Views?

**Comment by pp-mo** [comment]
> Views?

Well I think it makes sense, and is worth doing

**Comment by pp-mo** [comment]
Thinks we are done !
