### ISSUE TITLE
Time dimension in hybrid height

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#5369]
## ✨ Feature Request

[As described in CF conventions](https://cfconventions.org/cf-conventions/cf-conventions.html#atmosphere-hybrid-height-coordinate)

## Motivation

From @matthew-mizielinski. Considering how to represent hybrid height over glaciers, where the orography moves/changes over time.

## Additional context

@pp-mo expects problems with FF or PP loading, as it would require a specific sequence of merge steps.

<details>
<summary>Click to expand <b>this section...</b></summary>

```
Please add additional verbose information in this section e.g., references, screenshots, listings etc
```
</details>

```[tasklist]
### Tasks
- [ ] https://github.com/SciTools/iris/issues/6162
- [ ] https://github.com/SciTools/iris/issues/6163
- [ ] https://github.com/SciTools/iris/issues/6203
- [ ] https://github.com/SciTools/iris/issues/6204
```

**Comment by trexfeathers** [comment]
@matthew-mizielinski has confirmed that data like this currently generates 1 `Cube` for each time point, rather than a single `Cube` with a time dimension.

**Comment by trexfeathers** [comment]
It will be problematic for UK Met Office strategy (climate - IPCC) if this missed the 3.11 release.

**Comment by stephenworsley** [comment]
I believe it is currently possible to construct a hybrid height coordinate that varies over time. What is not possible is to merge multiple 2D cubes with varying orographies together. This would require a substantial change to merge behaviour. I suspect this may be covered by #5375 which has been a particularly stubborn issue to untangle.

**Comment by trexfeathers** [comment]
> I believe it is currently possible to construct a hybrid height coordinate that varies over time. What is not possible is to merge multiple 2D cubes with varying orographies together. This would require a substantial change to merge behaviour. I suspect this may be covered by #5375 which has been a particularly stubborn issue to untangle.

@stephenworsley let us know what you need. If necessary we have a whole team of developers (given the strategic importance of this).

**Comment by stephenworsley** [comment]
@matthew-mizielinski minimal test data would absolutely be appreciated, and yes, I think it would be good to set up a discussion when possible.

**Comment by stephenworsley** [comment]
One possible idea for resolving the merge issue:

Provide a keyword argument for the `merge` method which you can pass the name of an AuxCoord or a tuple of coord names. this tells `merge` which coordinates it ought to expand the dimensions of. Further information is likely to be required in the case where multiple dimensions are being added by `merge`, perhaps a tuple of dimension names in which to expand for each AuxCoord. This keyword could also be passed down from the `load` function.

This approach shouldn't break existing functionality and should allow sufficient controll of the merging process. I expect there may be some attention we would need to give to `AuxCoordFactory`s to make sure they behave sensibly during this process since I'm not aware of any other functions which add a dimension to a coordinate that another coordinate is derived from, but I don't expect this to be too much of a problem.

**Comment by stephenworsley** [comment]
An alternate approach to explore could involve concatenating instead of merging and using the `new_axis` utility to expand the dimensions of the orography coordinate appropriately. This ought to be enabled now via #4896, though I'm not sure how this handles derived coordinates.

**Comment by stephenworsley** [comment]
## Performance

Merging and concattenating can happen in any order and give the same result, however, it appears that _performance is heavily impacted_ when this happens.

Loading 60 of the above files:

- Applying `newaxis` takes ~20 seconds
- Merging first takes ~2.5 minutes
- Concattenating first takes ~30 minutes

It should be noted that in this case merging first combines cubes from within the same file and concattenating first involves combining cubes from differerent files. It's unclear if this would have a significant effect on performance.

**Comment by pp-mo** [comment]
All done now, v3.12
