### ISSUE TITLE
Improve utility of warnings in Iris tests

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#5466]
# Story

- As a
  Iris developer
- I want
  Warnings that are a problem for Iris to result in CI failure (e.g. a `DeprecationWarning`)
- So that
  I can address problems introduced by new commits **proactively** and **immediately** (rather than reactively when issues are discovered downstream)

# Notes

SciTools/iris#4384

Iris Gallery includes (or has included!) code to convert warnings to failures/errors.

# Ideas

- Suppress warnings we know are not a problem, so only those that matter are left. Then set a test run to exit non-`0` if any warnings are raised. Would likely need to address quite a few warnings before this could start working!
- A custom routine that causes a failure if it detects warnings of known categories (might only be `DeprecationWarning`?).

# From discussion

- Cost-benefit is difficult. Focussing on `DeprecationWarning` would be fairly easy, but is it offering much. Covering all warnings may need a lot of leg work to adapt the tests.
- Should start by seeing how many tests fail if warnings are 'promoted', and see how this informs further discussions.
```[tasklist]
### Tasks
- [ ] https://github.com/SciTools/iris/issues/5465
- [ ] https://github.com/SciTools/iris/issues/5491
- [ ] https://github.com/SciTools/iris/issues/5492
- [ ] https://github.com/SciTools/iris/pull/5493
- [ ] https://github.com/SciTools/iris/issues/5535
- [ ] https://github.com/SciTools/iris/issues/5534
- [ ] https://github.com/SciTools/iris/issues/5533
- [ ] https://github.com/SciTools/iris/issues/5530
- [ ] https://github.com/SciTools/iris/issues/5531
- [ ] https://github.com/SciTools/iris/issues/5532
- [ ] https://github.com/SciTools/iris/issues/5889
```

**Comment by ESadek-MO** [comment]
Note: have converted write up from #5465 into issues and added as subtasks on this issue.

**Comment by HGWright** [comment]
From @SciTools/peloton It would be a good idea to have the tests fail on DepricationWarnings, so that we are forced to address them. We have missed these in the past because the tests raise lots of warnings. https://docs.pytest.org/en/stable/reference/reference.html#confval-filterwarnings
