### ISSUE TITLE
Convert unit/common test files to pytest

### ISSUE THREAD

**Issue by bjlittle** [SciTools/iris#5820]
```[tasklist]
### Tasks
- [ ] https://github.com/SciTools/iris/pull/5822
- [ ] https://github.com/SciTools/iris/pull/5828
- [ ] https://github.com/SciTools/iris/pull/5842
- [ ] https://github.com/SciTools/iris/pull/5843
- [ ] https://github.com/SciTools/iris/pull/5845
- [ ] https://github.com/SciTools/iris/pull/5847
- [ ] https://github.com/SciTools/iris/pull/5849
- [ ] https://github.com/SciTools/iris/pull/5851
- [ ] https://github.com/SciTools/iris/pull/5852
- [ ] https://github.com/SciTools/iris/pull/5854
- [ ] https://github.com/SciTools/iris/pull/5868
- [ ] https://github.com/SciTools/iris/pull/5874
- [ ] https://github.com/SciTools/iris/pull/5875
- [ ] https://github.com/SciTools/iris/pull/5876
- [ ] https://github.com/SciTools/iris/pull/5878
- [ ] https://github.com/SciTools/iris/pull/5880
- [ ] https://github.com/SciTools/iris/pull/5881
- [ ] https://github.com/SciTools/iris/pull/5882
```
