### ISSUE TITLE
Implement the UGRID Location Index Set

### ISSUE THREAD

**Issue by trexfeathers** [SciTools/iris#6120]
## ✨ Feature Request

A new class that references an existing `Mesh`, offering access to all its properties/operations/etcetera, but actually subsetting that `Mesh`'s `Coord`s and `Connectivity`s as described by the [UGRID Location Index Set](https://ugrid-conventions.github.io/ugrid-conventions/#location-index-set) - effectively a 'view' on the original `Mesh`.

**This work is to be performed on the [`FEATURE_index_set`](https://github.com/SciTools/iris/tree/FEATURE_index_set) feature branch.**

## Motivation

This would provide a fuller implementation of UGRID within Iris, and is a viable solution to the following existing issues:

- #4751
- #4671
- It has been suggested [here](https://github.com/SciTools/iris/pull/6014#issue-2362588191) that this would provide more natural 'stitching' of a decomposed mesh, currently only available via [`recombine_submeshes`](https://github.com/SciTools/iris/blob/b8f554f7b8899f2ff6754857d59fc48944ef8e9b/lib/iris/mesh/utils.py#L18) - a highly specific proof-of-concept.

## Additional context

- Original proposal: https://github.com/SciTools/iris/issues/5991#issuecomment-2185937582
- First code attempts: #6014

```[tasklist]
### Tasks
- [ ] https://github.com/SciTools/iris/issues/6121
- [ ] https://github.com/SciTools/iris/issues/6122
- [ ] https://github.com/SciTools/iris/issues/5939
- [ ] https://github.com/SciTools/iris/issues/6123
- [ ] Investigate: `MeshIndexSet` use in `Mesh` decomposition and recombination
```
